const responseObj = {
  halo: "Halo! Apa kabar?",
  hai: "Hai! Ada yang bisa saya bantu?",
  "apa kabar": "Saya baik-baik saja!, bagaimana denganmu",
  "bagaimana hari ini": "Bagaimana hari Anda?",
  "selamat pagi": "Selamat pagi! Apa rencana hari ini?",
  "selamat siang": "Selamat siang! Ada yang bisa saya bantu?",
  "selamat sore": "Selamat sore! Apa yang bisa saya lakukan untuk Anda?",
  "selamat malam": "Selamat malam! Bagaimana hari Anda?",
  "ini ini": "Apa yang ingin Anda bicarakan?",
  cerita: "Ceritakan sesuatu yang menarik!",
  "kabar baik": "Kabar baik! Bagaimana dengan Anda?",
  "hari ini": 'new Date().toDateString()',
  waktu: '',
  baik: "Wah, senang mendengarnya",
  "saya ingin mengobrol": "Boleh, ceritakan semuanya!",
  "saya sedang bahagia karena hari ini saya makan eskrim":"Senang mendengarnya! Eskrim memang bisa menjadi penyemangat yang baik, apalagi saat cuaca sedang panas atau ketika Anda butuh sedikit kebahagiaan dalam hari yang sibuk. Ada rasa eskrim favorit yang Anda nikmati?",
  "jelaskan tentang apa itu internal pointer variable seperti saya berumur 5 tahun": "Tentu! Mari kita jelaskan dalam bahasa yang mudah dimengerti.<br>Internal pointer variable (variabel penunjuk internal) adalah sebuah konsep dalam pemrograman yang digunakan untuk melacak atau menunjuk ke alamat memori dari suatu nilai atau objek di dalam program komputer. Bayangkan kamu punya sebuah rumah (nilai atau objek), dan internal pointer variable adalah seperti peta yang menunjukkan di mana rumahmu berada.<br>Misalnya, kamu memiliki kotak berisi mainan, dan kamu ingin mengatakan ke temanmu di mana kotak itu berada. Kamu bisa memberi temanmu petunjuk seperti Kotak mainan itu ada di sudut ruangan sebelah kiri atas. Dalam dunia pemrograman, internal pointer variable berperan seperti petunjuk itu, memberitahu komputer di mana suatu nilai atau objek tersimpan di dalam memori.<br>Jadi, jika kamu berusia 5 tahun, mungkin akan sulit memahami konsep ini sepenuhnya sekarang, tetapi di kemudian hari ketika kamu belajar lebih banyak tentang pemrograman, kamu akan dapat memahaminya dengan lebih baik!",
  cuaca: "Cuacanya cukup menyenangkan hari ini.",
  "suasana hati": "Saya di sini untuk membantu, jadi silakan bagikan perasaan Anda.",
  minat: "Ceritakan tentang hobi dan minat Anda!",
  rencana: "Ada rencana menarik untuk hari ini?",
  berita: "Apakah Anda mendengar berita menarik belakangan ini?",
  lelucon: "Kenapa ilmuwan tidak percaya pada atom? Karena atom membuat segalanya!",
  "teka teki": "Saya berbicara tanpa mulut dan mendengar tanpa telinga. Saya tidak memiliki tubuh, tapi saya hidup dengan angin. Apa saya?",
  "warna kesukaan": "Warna kesukaan Anda apa? Saya suka biru!",
  musik: "Genre musik apa yang Anda sukai?",
  film: "Apakah Anda memiliki genre film favorit?",
  buku: "Apakah Anda telah membaca buku bagus belakangan ini?",
  "liburan Impian": "Jika Anda bisa pergi liburan impian, ke mana Anda akan pergi?",
  "hewan peliharaan": "Apakah Anda memiliki hewan peliharaan? Saya ingin mendengarnya!",
  "makanan kesukaan": "Makanan favorit Anda apa?",
  hobi: "Ceritakan tentang hobi favorit Anda!",
  "fakta acak": "Bagikan fakta acak dengan saya!",
  tujuan: "Apakah Anda memiliki tujuan atau aspirasi yang ingin Anda bicarakan?",
  prestasi: "Apa prestasi terbaru yang membuat Anda bangga?",
  tantangan: "Apa tantangan yang sedang Anda hadapi saat ini?",
  "rasa syukur": "Apa yang Anda syukuri hari ini?",
  inspirasi: "Apa yang menginspirasi Anda untuk terus maju ketika menghadapi kesulitan?",
  aspirasi: "Apa yang Anda harapkan dapat Anda capai di masa depan?",
  kenangan: "Bagikan kenangan indah dengan saya!",
  pertanyaan: "Apakah ada sesuatu yang ingin Anda tanyakan kepada saya?",
  "beri tahu saya hal yang lucu": "Hewan apa yang memiliki banyak keahlian? Kukang, bisa jadi kukang tambal ban, kukang servis motor dan kukang lainnya",
  "umpan balik?": "Saya selalu ingin meningkatkan diri. Apakah Anda punya umpan balik untuk saya?",
  "selamat tinggal?": "Senang berbincang dengan Anda! Semoga harimu menyenangkan!",
};

// Inisialisasi 'hari Ini' dan 'waktu' secara tertunda
defer(() => {
  responseObj.waktu = new Date().toLocaleTimeString();
});
